name: mrwebbeast
description: Products pagination.
publish_to: 'none' # Optional: If you're not publishing to any package repository

version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  # Local Data Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Navigation & State Management
  go_router: ^14.0.2
  provider: ^6.0.3
  # Networking
  http: ^1.1.0
  http_parser: ^4.0.2
  # Pagination
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.2.2


dev_dependencies:
  # Testing Framework
  flutter_test:
    sdk: flutter
  # Localization
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

